apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mtsn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-mtsn@sha256:00c71d94aef47955ac6eb6cad297fefcc22dc3522b803d743be3ec355665a456
        name: my-nodejs
        resources: {}
status: {}
